use once_cell::sync::Lazy;
use std::collections::HashMap;

/// Human-readable carrier and country for an (MCC, MNC) pair. `None` means "unknown" —
/// callers show the raw numeric identifiers instead.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Carrier {
    pub operator: Option<String>,
    pub country: Option<String>,
    pub country_code: Option<String>,
}

#[derive(serde::Deserialize)]
struct Row {
    mcc: u16,
    mnc: Option<u16>,
    operator: Option<String>,
    country: Option<String>,
    country_code: Option<String>,
}

/// Generated by `scripts/update-mcc-mnc.py` — never hand-edit.
static TABLE: Lazy<HashMap<(u16, Option<u16>), Carrier>> = Lazy::new(|| {
    csv::Reader::from_reader(include_str!("mcc-mnc.csv").as_bytes())
        .deserialize::<Row>()
        // ponytail: a malformed row can only come from a bad generator commit, so skip it and
        // serve nulls rather than panic in a request handler.
        .filter_map(Result::ok)
        .map(|row| {
            (
                (row.mcc, row.mnc),
                Carrier {
                    operator: row.operator,
                    country: row.country,
                    country_code: row.country_code,
                },
            )
        })
        .collect()
});

/// Exact `(mcc, net)` match; otherwise the country the MCC is dominated by, with no operator.
pub fn lookup(mcc: u16, net: u16) -> Carrier {
    if let Some(carrier) = TABLE.get(&(mcc, Some(net))) {
        return carrier.clone();
    }
    match TABLE.get(&(mcc, None)) {
        Some(carrier) => Carrier {
            operator: None,
            ..carrier.clone()
        },
        None => Carrier::default(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_known_pair_returns_operator_country_and_code() {
        let carrier = lookup(262, 2);

        assert_eq!(carrier.operator.as_deref(), Some("Vodafone"));
        assert_eq!(carrier.country.as_deref(), Some("Germany"));
        assert_eq!(carrier.country_code.as_deref(), Some("DE"));
    }

    #[test]
    fn test_unknown_mnc_returns_null_operator_but_keeps_country() {
        let carrier = lookup(262, 999);

        assert_eq!(carrier.operator, None);
        assert_eq!(carrier.country.as_deref(), Some("Germany"));
        assert_eq!(carrier.country_code.as_deref(), Some("DE"));
    }

    #[test]
    fn test_unknown_mcc_returns_all_null() {
        assert_eq!(lookup(999, 1), Carrier::default());
    }

    #[test]
    fn test_two_digit_source_mnc_matches_integer_net() {
        // The source records this MNC as "01"; OpenCelliD stores net as an integer.
        assert_eq!(lookup(262, 1).operator.as_deref(), Some("Telekom"));
    }

    #[test]
    fn test_three_digit_source_mnc_matches_integer_net() {
        assert_eq!(lookup(310, 260).operator.as_deref(), Some("T-Mobile"));
    }

    #[test]
    fn test_multi_country_mcc_uses_row_country() {
        let carrier = lookup(310, 120);

        assert_eq!(
            carrier.country.as_deref(),
            Some("United States Virgin Islands")
        );
        assert_eq!(carrier.country_code.as_deref(), Some("VI"));
    }
}
